name: Software Build Attestation

on:
  release:
    types: [published]

jobs:
  build:
    permissions: write-all
    runs-on: [reproducible-build]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        attestable-build-tool build -output phat-hello -nitro ~/ata-build-phala-latest.eif -vendor ata-build-phala -mem 10240
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: phat-hello.txt
        append_body: true
        files: |
          phat-hello.report
          phat-hello.tar
